### ISSUE TITLE
Using shellcheck and resholve

### ISSUE THREAD

**Issue by manveru** [clhodapp/nix-runner#3]
Would it be possible to pass the scripts first through shellcheck and resholve?

**Comment by clhodapp** [comment]
Hmmm... I guess I'll tackle these separately.

For resholve: I love `resholve` for packaged scripts but I am not sure what value it would provide for this use-case vs just tightly controlling `PATH`, as `#!pure` does. Furthermore, adding a resholve option would necessitate also adding options to for all of resholve's configuration (which is nontrivial and so not something I'm super-interested to maintain without strong cause). Am I missing an important benefit?

For shellcheck: I don't really see the value in forcing the script to be linted every single time you run it (including potentially on other people's machines) vs just running normal shellcheck on it on-demand.

**Comment by clhodapp** [comment]
Hey, @manveru, wanted to let you know that I'm thinking of closing this soon in case you're aware of use cases that I'm not thinking of.
